package co.uk.bbk.culinarycompanion_enriketashehi

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class representing a single recipe in the Room database.
 *
 * Each instance of this class corresponds to a row in the "recipe" table.
 */
@Entity(tableName= "recipe")
data class Recipe (
    /** Unique ID for each recipe (auto-generated by Room). */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,

    /** Title of the recipe (e.g. "Lentil Soup"). */
    val title: String,

    /** Short preview text shown in recipe lists (e.g. "Hearty soup with lentils..."). */
    val preview: String,

    /** Ingredients required for the recipe, stored as a multi-line string. */
    val ingredients: String,

    /** Cooking instructions for preparing the recipe. */
    val instructions: String,

    /** Category for organizing recipes (e.g. "Dinner", "Desserts"). */
    val category: String
)